module.exports = client => {
  client.emojisByName = {
    'stopwatch': '\u23f1',
    'timer': '\u23f2',
    'information_source': '\u2139',
    'heart': '\u2764',
    'regional_indicator_a': String.fromCodePoint(0x1f1e6),
    'regional_indicator_b': String.fromCodePoint(0x1f1e7),
    'regional_indicator_c': String.fromCodePoint(0x1f1e8),
    'regional_indicator_d': String.fromCodePoint(0x1f1e9),
    'regional_indicator_e': String.fromCodePoint(0x1f1ea),
    'regional_indicator_f': String.fromCodePoint(0x1f1eb),
    'regional_indicator_g': String.fromCodePoint(0x1f1ec),
    'regional_indicator_h': String.fromCodePoint(0x1f1ed),
    'regional_indicator_i': String.fromCodePoint(0x1f1ee),
    'regional_indicator_j': String.fromCodePoint(0x1f1ef),
    'regional_indicator_k': String.fromCodePoint(0x1f1f0),
    'regional_indicator_l': String.fromCodePoint(0x1f1f1),
    'regional_indicator_m': String.fromCodePoint(0x1f1f2),
    'regional_indicator_n': String.fromCodePoint(0x1f1f3),
    'regional_indicator_o': String.fromCodePoint(0x1f1f4),
    'regional_indicator_p': String.fromCodePoint(0x1f1f5),
    'regional_indicator_q': String.fromCodePoint(0x1f1f6),
    'regional_indicator_r': String.fromCodePoint(0x1f1f7),
    'regional_indicator_s': String.fromCodePoint(0x1f1f8),
    'regional_indicator_t': String.fromCodePoint(0x1f1f9),
    'regional_indicator_u': String.fromCodePoint(0x1f1fa),
    'regional_indicator_v': String.fromCodePoint(0x1f1fb),
    'regional_indicator_w': String.fromCodePoint(0x1f1fc),
    'regional_indicator_x': String.fromCodePoint(0x1f1fd),
    'regional_indicator_y': String.fromCodePoint(0x1f1fe),
    'regional_indicator_z': String.fromCodePoint(0x1f1ff),
    'a': String.fromCodePoint(0x1f170),
    'b': String.fromCodePoint(0x1f171),
    'o2': String.fromCodePoint(0x1f17e),
    'doge': ':doge:391497526278225920',
  };
};
